version: '3.9'
services:
  deno_api:
    container_name: 'deno_api'
    env_file: .env
    build: .
    ports:
      - target: ${SERVER_PORT}
        published: 3000
  nginx:
    image: 'nginx:1.21.3-alpine'
    container_name: 'nginx'
    volumes:
      - ./templates:/etc/nginx/templates
      - ./public:/data/www
    ports:
      - '80:80'
    environment:
      - NGINX_PORT=80
      - API_URL=deno_api
      - API_PORT=3000
    depends_on:
      - deno_api
